Remove stateful `app.settings.accessToken`
feathersjs/feathers-authentication-client pull request #99
Opened 2018-04-18 19:16 UTC by roemhildtg

### Summary

I'd like to open a discussion on eliminating the stored `accessToken` on the app object. Setting `accessToken` on the app introduces a bug in ssr where there is a stateful `accessToken` being set in the feathers object. DoneJS, for instance doesn't reload all of its client files between requests and instead uses a zone-safe storage object for cookies, etc. When another user accesses the same ssr server, `accessToken` is already set and that access token is used to access rest api's from the ssr server, resulting in a user impersonating someone else.

This pull request replaces `app.get('accessToken')` with `app.get('storage').getItem('accessToken');` `app` is a stateful object that shouldn't be used to store information about a user cookie. The storage property on the app is already used in a few places, so there's nothing added there, I am however getting rid `accessToken`, a property that might be used in places so I'm not sure of the potential pitfalls of this.

- [x] Tell us about the problem your pull request is solving.
- [ ] Are there any open issues that are related to this?
- [x] Is this PR dependent on PRs in other repos?

### Other Information

 - https://github.com/canjs/can-connect-feathers/issues/111
 - https://github.com/canjs/can-connect-feathers/issues/77

2018-04-18 19:31 UTC, roemhildtg commented
Okay, lots of errors in the tests. I can go about fixing these in additional commits, but before I get too far, I'd like to get some feedback if this is the right solution or is there a different approach I should be taking.

2018-05-01 04:31 UTC, marshallswain commented
This is something that caught me up when integrating DoneSSR many times, so I'd love to see this land.  @roemhildtg, let me know if you need any assistance.

2018-05-11 17:27 UTC, foxhound87 commented
I got this issue too, it is very harmful and should be addressed asap!
Please provide a completely stateless authentication mechanism!

Thanks.

2018-05-17 21:58 UTC, roemhildtg commented
Hi guys. I haven't forgotten about this! I'm just in the middle of moving and have been pretty busy lately. I hope to have time in the next month or so to finish this.

2018-06-14 16:42 UTC, daffl requested changes
The tests should be passing as well.

2018-06-14 16:42 UTC, daffl commented on lib/hooks/populate-access-token.js
> +    Object.assign(hook.params, { accessToken: app.get('storage').getItem(app.passport.options.storageKey) });
This needs to work asynchronously (for React Natives `AsyncStorage`):

```js
return Promise.resolve(app.get('storage').getItem(app.passport.options.storageKey)).then(accessToken => {
  Object.assign(hook.params, { accessToken });
  return hook;
});
```

2018-07-18 23:57 UTC, roemhildtg commented
These are (mostly) passing for me (on windows). 

There are 4 that won't run though...they are just stuck in pending for some reason.

![image](https://user-images.githubusercontent.com/5471079/42913776-693e95aa-8abc-11e8-97a3-698e5aa2c1b9.png)

2018-08-28 23:43 UTC, bparise commented
Is there a current workaround for this?  It took me days to figure out why state was persisting when running this inside of Nuxtjs with SSR.  I moved my calls to just using `this.$axios.$post('/authentication')` but was curious if there was another workaround so I can continue to use this module.

2018-08-29 02:31 UTC, roemhildtg commented
AFAIK the workaround for now is to check for ssr in your Auth implementation and if using ssr, return not authenticated on the server. If on the client browser authenticate then update view to represent authenticated state.

2018-09-28 01:28 UTC, roemhildtg commented
Hey @marshallswain I'd like to see the solution to this merged for a donejs project. Any tips you can offer on getting these tests to pass?

2019-04-22 23:06 UTC, daffl commented
This has been included in Feathers v4 authentication. Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this PR in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).

2019-04-22 23:06 UTC, closed without merging